version: 2.1
jobs:
  build:
    docker:
      - image: cimg/node:18.17.0
      - image: cimg/postgres:14.6
        environment:
          POSTGRES_PASSWORD: odktest

    working_directory: ~/repo

    steps:
      - checkout
      - run: make check-file-headers
      - run: npm ci --legacy-peer-deps
      - run: node lib/bin/create-docker-databases.js
      - run: make test-full

